name: animated_icon
description: This package support a animated icon with some customization like color, animate, hover, callback.
version: 0.0.3
homepage: https://github.com/mi-ghanshyam/animated_icons

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  assets:
    - assets/
